export const products = [
  {
    name: "Pods 1",
    price: "$14.99",
    description: "Wireless earbuds with compact design and long battery life.",
    image: "./img/pods1.webp",
  },
  {
    name: "Pods 2",
    price: "$16.99",
    description: "Noise-cancelling earbuds in a sleek black finish.",
    image: "./img/pods2.webp",
  },
  {
    name: "Pods 3",
    price: "$15.49",
    description: "Comfortable wireless earbuds with smooth pairing.",
    image: "./img/pods3.webp",
  },
  {
    name: "Pods 4",
    price: "$18.99",
    description: "Sporty earbuds with dual microphones for clear calls.",
    image: "./img/pods4.webp",
  },
  {
    name: "Watch 1",
    price: "$39.99",
    description: "Smartwatch with vibrant display and fitness tracking.",
    image: "./img/w-1.webp",
  },
  {
    name: "Watch 2",
    price: "$42.99",
    description: "Rugged smartwatch with multiple sports modes.",
    image: "./img/w-2.webp",
  },
  {
    name: "Watch 3",
    price: "$37.49",
    description: "Stylish smartwatch with metallic finish.",
    image: "./img/w-3.webp",
  },
  {
    name: "Watch 4",
    price: "$35.99",
    description: "Smartwatch with health monitoring features.",
    image: "./img/w-4.webp",
  },
  {
    name: "Watch 5",
    price: "$33.99",
    description: "Minimalist smartwatch with full-screen display.",
    image: "./img/w-5.webp",
  },
  {
    name: "Watch 6",
    price: "$31.99",
    description: "Hybrid design smartwatch with leather strap.",
    image: "./img/w-6.webp",
  },
  {
    name: "Watch 7",
    price: "$34.49",
    description: "Tough design watch with advanced sensors.",
    image: "./img/w-7.webp",
  },
  {
    name: "Zero Pods 1",
    price: "$21.99",
    description: "Glossy blue true wireless earbuds with rich sound.",
    image: "./img/zero-1.webp",
  },
  {
    name: "Zero Pods 2",
    price: "$22.99",
    description: "Compact case wireless earbuds with high clarity audio.",
    image: "./img/zero-2.webp",
  },
  {
    name: "Zero Pods 3",
    price: "$24.49",
    description: "Dual-tone finish earbuds with enhanced bass.",
    image: "./img/zero-3.webp",
  },
  {
    name: "White Adaptor",
    price: "$8.99",
    description: "Compact USB power adapter for quick and safe charging.",
    image: "./img/adaptor.webp",
  },
  {
    name: "Black Adaptor",
    price: "$10.99",
    description: "High-speed charging adaptor with sleek black design.",
    image: "./img/adaptor-2.webp",
  },
  {
    name: "Chain Strap",
    price: "$6.49",
    description: "Durable and stylish chain strap for smartwatches.",
    image: "./img/chain-strap.webp",
  },
  {
    name: "Charging Cable",
    price: "$4.99",
    description: "Fast charging Type-A to Micro USB cable.",
    image: "./img/charging-cable.webp",
  },
  {
    name: "Handsfree 1",
    price: "$5.99",
    description: "Wired handsfree with crystal-clear sound quality.",
    image: "./img/handsfree-1.webp",
  },
  {
    name: "Handsfree 2",
    price: "$6.99",
    description: "Comfortable fit with noise isolation.",
    image: "./img/handsfree-2.webp",
  },
  {
    name: "Handsfree 3",
    price: "$5.49",
    description: "Classic handsfree for daily use with built-in mic.",
    image: "./img/handsfree-3.webp",
  },
  {
    name: "Headphone 2",
    price: "$19.99",
    description: "Over-ear wired headphones with deep bass.",
    image: "./img/headphone-2.webp",
  },
  {
    name: "Headphone 3",
    price: "$22.49",
    description: "Stylish design and high-quality audio.",
    image: "./img/headphone-3.webp",
  },
  {
    name: "Headphone 4",
    price: "$24.99",
    description: "Premium wired headphones for immersive sound.",
    image: "./img/headphone-4.webp",
  },
  {
    name: "Headphone 5",
    price: "$18.99",
    description: "Affordable option with clear audio and mic.",
    image: "./img/headphone-5.webp",
  },
  {
    name: "Headphone 6",
    price: "$20.99",
    description: "Balanced sound, perfect for calls and music.",
    image: "./img/headphone-6.webp",
  },
  {
    name: "Leather Strap",
    price: "$7.99",
    description: "Genuine leather strap for a classy watch look.",
    image: "./img/leather-strap.webp",
  },
  {
    name: "Neck Band",
    price: "$13.99",
    description: "Bluetooth neckband with long battery life.",
    image: "./img/neck-band.webp",
  },
  {
    name: "OTG Adapter",
    price: "$3.99",
    description: "Mini USB OTG adapter for file transfer and accessories.",
    image: "./img/otg.webp",
  },
  {
    name: "Power Bank 1",
    price: "$29.99",
    description: "10,000mAh portable charger with dual USB ports.",
    image: "./img/powerbank-1.webp",
  },
  {
    name: "Power Bank 2",
    price: "$34.99",
    description: "Slim power bank with fast charging support.",
    image: "./img/powerbank-2.webp",
  },
  {
    name: "Smart Tracker",
    price: "$14.99",
    description: "Bluetooth tracker to locate your essentials quickly.",
    image: "./img/smart-tracker.webp",
  },
  {
    name: "Speaker",
    price: "$16.99",
    description: "Portable speaker with rich bass and Bluetooth 5.0.",
    image: "./img/speaker.webp",
  },
  {
    name: "Type-C Charging Cable",
    price: "$5.99",
    description: "Durable and fast USB Type-C charging cable.",
    image: "./img/type-c-charging.webp",
  },
];
